server:
  port: 8016

spring:
  mvc:
    servlet:
      path: /time
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/cykb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: false

logging:
  level:
    # ????
    root: warn
    com: info
  file:
    name: logs/time.log